name: Compare

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base versions (dep@version, comma-separated) or date"
        default: "webpack@webpack/webpack#master"
        required: true
      current:
        description: "current versions (dep@version, comma-separated) or date"
        default: "webpack@webpack/webpack#master"
        required: true

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        base:
          - "${{ github.event.inputs.base }}"
        current:
          - "${{ github.event.inputs.current }}"
        case:
          - common-libs
          - esbuild-three
          - rome
        scenario:
          - development-build
          - development-build+initial-persistent-cache
          - development-build+persistent-cache
          - development-rebuild
          - development-rebuild+unsafe-cache
          - production-build
          - production-build+source-map
          - production-build+source-map+babel-env
          - production-build+no-minimize
          - production-build+persistent-cache
          - production-build+initial-persistent-cache
          - production-build+source-map+persistent-cache
          - production-build+source-map+initial-persistent-cache
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 25
          command: node bin/compare.js ${{ matrix.case }} ${{ matrix.scenario }} ${{ github.event.inputs.base }} ${{ github.event.inputs.current }}
      - uses: actions/upload-artifact@v4
        with:
          name: compare-results-${{ matrix.case }}-${{ matrix.scenario }}-${{ github.event.inputs.base }}-${{ github.event.inputs.current }}
          path: output
  report:
    needs: [bench]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: actions/download-artifact@v4
        with:
          path: output
          pattern: compare-results-*
          merge-multiple: true
      - run: node bin/report.js
