name: Measure single data point

on:
  workflow_dispatch:
    inputs:
      case:
        description: "Case to measure"
        default: "common-libs"
        required: true
      scenario:
        description: "Scenario to measure"
        default: "development-build"
        required: true
      date:
        description: "Date to measure (yyyy-mm-dd)"
        default: "2021-10-01"
        required: true
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js ${{ github.event.inputs.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: node bin/upload.js ${{ github.event.inputs.date }} ${{ secrets.GITHUB_TOKEN }}
