name: Measure scenario and date for all cases

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "Scenario to measure"
        default: "development-build"
        required: true
      date:
        description: "Date to measure (yyyy-mm-dd)"
        default: "2021-10-01"
        required: true

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        case:
          - common-libs
          - esbuild-three
          - rome
          - atlaskit-editor
          - common-libs-chunks
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js ${{ matrix.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: measure-results-${{ matrix.case }}-${{ github.event.inputs.scenario }}-${{ github.event.inputs.date }}
          path: output
  upload:
    needs: [bench]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: output
          pattern: measure-results-*
          merge-multiple: true
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: node bin/upload.js ${{ github.event.inputs.date }} ${{ secrets.GITHUB_TOKEN }}
