name: Measure date

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date to measure (yyyy-mm-dd)"
        default: "2021-01-01"
        required: true
jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        case:
          - common-libs
          - esbuild-three
          - rome
          - atlaskit-editor
          - common-libs-chunks
        scenario:
          - development-build
          - development-build+initial-persistent-cache
          - development-build+persistent-cache
          - development-rebuild
          - development-rebuild+unsafe-cache
          - development-rebuild+unsafe-cache+no-exports-analysis
          - development-rebuild+persistent-cache+unsafe-cache+no-exports-analysis
          - production-build
          - production-build+source-map
          - production-build+source-map+babel-env
          - production-build+no-minimize
          - production-build+persistent-cache
          - production-build+initial-persistent-cache
          - production-build+source-map+persistent-cache
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.date }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js ${{ matrix.case }} ${{ matrix.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: measure-results-${{ matrix.case }}-${{ matrix.scenario }}-${{ github.event.inputs.date }}
          path: output
  upload:
    needs: [bench]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.date }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "yarn"
      - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: output
          pattern: measure-results-*
          merge-multiple: true
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: node bin/upload.js ${{ github.event.inputs.date }} ${{ secrets.GITHUB_TOKEN }}
